#!/bin/bash


usermod -l lukebakare ubuntu
groupmod -n lukebakare ubuntu
usermod -d /home/lukebakare -m lukebakare
usermod -c "lukebakare" lukebakare

echo 'lukebakare ALL=(ALL) NOPASSWD: ALL' | EDITOR='tee -a' visudo

apt-get update

DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
